const translations = {
  en: {
    // Navbar / general
    home: "Home",
    Chara: "Character Creator",
    NameGen: "Name Generator",
    NameGenFantasy: "Fantasy Name Generator",
    PowerScaling: "Power Scaling",
    Leveling: "Leveling",

    // Index page
    indextitle: "D&D Character Forge",
    subtitle: "Create heroes, legends, and wanderers of the wilds.",
    dnddesc: "D&D 5e–accurate character creator",
    saveloaddesc: "Save & load characters locally",
    namegendesc: "Fantasy name generator",
    powerscalingdesc: "Power scaling & point-buy",
    ambientdesc: "Ambient forest visuals",

    // Power Scaling page
    PowerScalingDescriptionLong: "This page uses your saved character to calculate overall strength.",
    PowerScalingButton: "Calculate Power",

    // Name Generator page
    NameGenFantasyButton: "Generate Name",

    // Character Creator page labels (from before)
    legendBasic: "Basic",
    legendStats: "Statistics",
    legendExtra: "Extra",
    firstNameLabel: "First Name",
    lastNameLabel: "Last Name",
    customRaceLabel: "Custom Race",
    alignmentLabel: "Alignment",
    alignmentLG: "Lawful Good",
    alignmentNG: "Neutral Good",
    alignmentCG: "Chaotic Good",
    alignmentLN: "Lawful Neutral",
    alignmentTN: "True Neutral",
    alignmentCN: "Chaotic Neutral",
    alignmentLE: "Lawful Evil",
    alignmentNE: "Neutral Evil",
    alignmentCE: "Chaotic Evil",
    STR: "STR",
    DEX: "DEX",
    CON: "CON",
    INT: "INT",
    WIS: "WIS",
    CHA: "CHA",
    ageLabel: "Age",
    heightLabel: "Height",
    weightLabel: "Weight",
    sexLabel: "Sex",
    genderLabel: "Gender",
    notesLabel: "Notes / Backstory",
    saveBtn: "Save",
    exportBtn: "Export",
    resetBtn: "Reset",
    previewTitle: "Character Preview",
    female: "female",
    male: "male",
    intersex: "intersex",
	
	// Character Creator specifics
    child: "Child",
    adult: "Adult",
    elder: "Elder",
    lifespan: "Average lifespan: {years} years",
    manualMode: "Manual",
    manualTooltip: "Type any number for stats",
    randomDropMode: "Random (4d6)",
    randomDropTooltip: "Roll 4d6 and drop the lowest die",
    randomAllMode: "Random (3d6)",
    randomAllTooltip: "Roll 3d6 sum all dice'",
    pointBuyMode: "Point Buy",
    pointBuyTooltip: "Distribute 27 points using DnD point-buy rules",
	randomBtn: "Random",
	
	//Rasy
	raceHuman: "Human",
	raceElf: "Elf",
	raceDwarf: "Dwarf",
	raceHalfling: "Halfling",
	raceDragonborn: "Dragonborn",
	raceGnome: "Gnome",
	raceHalfElf: "Half-Elf",
	raceHalfOrc: "Half-Orc",
	raceTiefling: "Tiefling",
	raceOrc: "Orc",
	raceGoblin: "Goblin",
	raceTabaxi: "Tabaxi",
	raceKenku: "Kenku",
	raceLizardfolk: "Lizardfolk",
    raceCustom: "Custom",
	
	//Leveling
    levelingHeader: "Character Leveling",
    levelUp: "Level Up",
    chooseClass: "Choose Class",
    startLevelBtn: "Start Level-Up",
    levelChoices: "Level Choices",
    confirmLevelBtn: "Confirm Level",
    levelHistory: "Level History",
    loadBtn: "Export",
    importBtn: "Import",
    resetBtn: "Reset",
    noChoices: "No choices required at this level.",
    subclass: "Subclass",
    classLabel: "Class",
    levelLabel: "Level",
    choose: "choose",
    asiFeat: "ASI / Feat",
    ASI: "ASI",
    Feat: "Feat",
    selectedFeat: "Selected Feat",
    spells: "Spells",
	
	//Classes
    barbarian: "Barbarian",
    bard: "Bard",
    cleric: "Cleric",
    druid: "Druid",
    fighter: "Fighter",
    monk: "Monk",
    paladin: "Paladin",
    ranger: "Ranger",
    rogue: "Rogue",
    sorcerer: "Sorcerer",
    warlock: "Warlock",
    wizard: "Wizard",
    artificer: "Artificer",

    // Subclasses
    berserker: "Berserker",
    totemWarrior: "Totem Warrior",
    lore: "Lore",
    valor: "Valor",
    knowledge: "Knowledge",
    life: "Life",
    light: "Light",
    natureSub: "Nature",
    tempest: "Tempest",
    trickery: "Trickery",
    warSub: "War",
    land: "Land",
    moon: "Moon",
    champion: "Champion",
    battleMaster: "Battle Master",
    eldritchKnight: "Eldritch Knight",
    openHand: "Open Hand",
    shadow: "Shadow",
    fourElements: "Four Elements",
    devotion: "Devotion",
    ancients: "Ancients",
    vengeance: "Vengeance",
    hunter: "Hunter",
    beastMaster: "Beast Master",
    thief: "Thief",
    assassin: "Assassin",
    arcaneTrickster: "Arcane Trickster",
    draconicBloodline: "Draconic Bloodline",
    wildMagic: "Wild Magic",
    archfey: "Archfey",
    fiend: "Fiend",
    greatOldOne: "Great Old One",
    abjuration: "Abjuration",
    conjuration: "Conjuration",
    divination: "Divination",
    enchantment: "Enchantment",
    evocation: "Evocation",
    illusion: "Illusion",
    necromancy: "Necromancy",
    transmutation: "Transmutation",

    // Skills
    "Animal Handling": "Animal Handling",
    Athletics: "Athletics",
    Intimidation: "Intimidation",
    Nature: "Nature",
    Perception: "Perception",
    Survival: "Survival",
    History: "History",
    Insight: "Insight",
    Medicine: "Medicine",
    Persuasion: "Persuasion",
    Religion: "Religion",
    Arcana: "Arcana",
    Acrobatics: "Acrobatics",
    Deception: "Deception",
    Investigation: "Investigation",
    Performance: "Performance",
    "Sleight of Hand": "Sleight of Hand",
    Stealth: "Stealth"
	
  },
  pl: {
    // Navbar / general
    home: "Strona główna",
    Chara: "Kreator Postaci",
    NameGen: "Generator Imion",
    NameGenFantasy: "Generator Imion Fantasy",
    PowerScaling: "Skalowanie Mocy",
    Leveling: "Levelowanie",

    // Index page
    indextitle: "D&D Kuźnia Postaci",
    subtitle: "Twórz bohaterów, legendy i wędrowców lasów.",
    dnddesc: "Tworzenie postaci zgodne z D&D 5e",
    saveloaddesc: "Zapisuj i wczytuj postacie lokalnie",
    namegendesc: "Generator fantastycznych imion",
    powerscalingdesc: "Skalowanie mocy i punktów",
    ambientdesc: "Efekty wizualne magicznego lasu",

    // Power Scaling page
    PowerScalingDescriptionLong: "Ta strona wykorzystuje zapisaną postać do obliczenia całkowitej siły.",
    PowerScalingButton: "Oblicz Moc",

    // Name Generator page
    NameGenFantasyButton: "Generuj Imię",

    // Character Creator page labels (from before)
    legendBasic: "Podstawowe",
    legendStats: "Statystyki",
    legendExtra: "Dodatkowe",
    firstNameLabel: "Imię",
    lastNameLabel: "Nazwisko",
    raceCustom: "Własna",
    customRaceLabel: "Własna Rasa",
    alignmentLabel: "Punkty Charakteru",
    alignmentLG: "Praworządny Dobry",
    alignmentNG: "Neutralny Dobry",
    alignmentCG: "Chaotyczny Dobry",
    alignmentLN: "Praworządny Neutralny",
    alignmentTN: "Prawdziwie Neutralny",
    alignmentCN: "Chaotyczny Neutralny",
    alignmentLE: "Praworządny Zły",
    alignmentNE: "Neutralny Zły",
    alignmentCE: "Chaotyczny Zły",
    STR: "SIŁA",
    DEX: "ZRĘCZNOŚĆ",
    CON: "KONSTYTUCJA",
    INT: "INTELIGENCJA",
    WIS: "MĄDROŚĆ",
    CHA: "CHARYZMA",
    ageLabel: "Wiek",
    heightLabel: "Wzrost",
    weightLabel: "Waga",
    notesLabel: "Notatki / Historia",
    sexLabel: "Płeć (biologiczna)",
    genderLabel: "Płeć",
    saveBtn: "Zapisz",
    exportBtn: "Eksportuj",
    loadBtn: "Eksportuj",
    resetBtn: "Resetuj",
    previewTitle: "Podgląd Postaci",
    female: "żeńska",
    male: "męska",
    intersex: "interpłciowa",
	
	// Character Creator specifics
    child: "Dziecko",
    adult: "Dorosły",
    elder: "Starszy",
    lifespan: "Średnia długość życia: {years} lat",
    manualMode: "Ręcznie",
    manualTooltip: "Wpisz dowolną liczbę dla statystyk",
    randomDropMode: "Losowe (4d6)",
    randomDropTooltip: "Rzuc 4k6 i odrzuć najniższy",
    randomAllMode: "Losowe (3d6)",
    randomAllTooltip: "Rzuć 3k6 i sumuj wszystkie",
    pointBuyMode: "Punkty",
    pointBuyTooltip: "Rozdziel 27 punktów według zasad DnD",
	randomBtn: "Losuj",
	
	//Rasy
	raceHuman: "Człowiek",
	raceElf: "Elf",
	raceDwarf: "Krasnolud",
	raceHalfling: "Półling",
	raceDragonborn: "Dragonborn",
	raceGnome: "Gnom",
	raceHalfElf: "Półelf",
	raceHalfOrc: "Półork",
	raceTiefling: "Tiefling",
	raceOrc: "Ork",
	raceGoblin: "Goblin",
	raceTabaxi: "Tabaxi",
	raceKenku: "Kenku",
	raceLizardfolk: "Jaszczuroczłek",
    raceCustom: "Własna",
	
	//Leveling
    levelingHeader: "Poziomowanie Postaci",
    levelUp: "Awans",
    chooseClass: "Wybierz Klasę",
    startLevelBtn: "Rozpocznij awans",
    levelChoices: "Opcje awansu",
    confirmLevelBtn: "Potwierdź poziom",
    levelHistory: "Historia poziomów",
    loadBtn: "Eksportuj",
    importBtn: "Importuj",
    resetBtn: "Resetuj",
    noChoices: "Ten poziom nie wymaga wyborów.",
    subclass: "Podklasa",
    classLabel: "Klasa",
    levelLabel: "Poziom",
    choose: "wybierz",
    asiFeat: "B/O (Wzrost cech / Feat)",
    ASI: "B/O",
    Feat: "Feat",
    selectedFeat: "Wybrany Feat",
    spells: "Zaklęcia",
	//Classes
    barbarian: "Barbarzyńca",
    bard: "Bard",
    cleric: "Kapłan",
    druid: "Druid",
    fighter: "Wojownik",
    monk: "Mnich",
    paladin: "Paladyn",
    ranger: "Łowca",
    rogue: "Łotrzyk",
    sorcerer: "Czarodziej",
    warlock: "Czarownik",
    wizard: "Mag",
    artificer: "Artyfiser",

    // Subclasses
    berserker: "Berserker",
    totemWarrior: "Wojownik Totemiczny",
    lore: "Wiedza",
    valor: "Odwaga",
    knowledge: "Wiedza",
    life: "Życie",
    light: "Światło",
    natureSub: "Natura",
    tempest: "Burza",
    trickery: "Podstęp",
    warSub: "Wojna",
    land: "Ziemia",
    moon: "Księżyc",
    champion: "Mistrz",
    battleMaster: "Mistrz Bitewny",
    eldritchKnight: "Rycerz Czarodziej",
    openHand: "Otwarta Dłoń",
    shadow: "Cień",
    fourElements: "Cztery Żywioły",
    devotion: "Oddanie",
    ancients: "Pradawni",
    vengeance: "Zemsta",
    hunter: "Łowca",
    beastMaster: "Pan Bestii",
    thief: "Złodziej",
    assassin: "Zabójca",
    arcaneTrickster: "Arkaniczny Oszust",
    draconicBloodline: "Smocza Krew",
    wildMagic: "Dzika Magia",
    archfey: "Archiwiedźma",
    fiend: "Demon",
    greatOldOne: "Wielki Stary",
    abjuration: "Abjuracja",
    conjuration: "Konjuracja",
    divination: "Wróżbiarstwo",
    enchantment: "Urok",
    evocation: "Ewokacja",
    illusion: "Iluzja",
    necromancy: "Nekromancja",
    transmutation: "Transmutacja",

    // Skills
    "Animal Handling": "Opanowanie zwierząt",
    Athletics: "Atletyka",
    Intimidation: "Zastraszanie",
    Nature: "Natura",
    Perception: "Percepcja",
    Survival: "Przetrwanie",
    History: "Historia",
    Insight: "Spostrzegawczość",
    Medicine: "Medycyna",
    Persuasion: "Perswazja",
    Religion: "Religia",
    Arcana: "Arcana",
    Acrobatics: "Akrobatyka",
    Deception: "Oszustwo",
    Investigation: "Śledztwo",
    Performance: "Występ",
    "Sleight of Hand": "Zręczne ręce",
    Stealth: "Skrytobójstwo"
	
  }
};

// Translation function
function setLang(lang) {
  localStorage.setItem("lang", lang);
  const t = translations[lang] || {};

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (key && t[key] !== undefined) {
      el.textContent = t[key];
    }
  });
}

// Apply saved language on page loa
